# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Install dependencies and server
COPY pyproject.toml .
COPY analytics_mcp ./analytics_mcp
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir .

ENTRYPOINT ["google-analytics-mcp"]
